#!/user/bin/python3

tlgfolks= ["Aaron", "Adrian", "Alex", "Tony", "Chris", "Derek", "Javier", "John", "Jonathan", "Justin", "Levi", "Rohalio", "Steven", "Taje", "Trent", "Walt"]

for eachperson in tlgfolks:
    if eachperson.startswith("J")
        print(eachperson + " is awesome!")
